version: '3.7'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8.2
    hostname: zookeeper
    networks:
      - application
    ports:
      - "2181:2181"
    environment:
      ZOO_PORT_NUMBER: 2181
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka-broker:
    image: bitnami/kafka:3.5.1
    hostname: kafka-broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:19092,LISTENER_LOCAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:19092,LISTENER_LOCAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: LISTENER_LOCAL
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - application

networks:
  application:
    driver: bridge